
package client_async;

import java.util.concurrent.Future;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.AsyncHandler;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.Response;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "CheckPayService", targetNamespace = "http://service/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CheckPayService {


    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns javax.xml.ws.Response<client_async.CheckPayResponse>
     */
    @WebMethod(operationName = "CheckPay")
    @RequestWrapper(localName = "CheckPay", targetNamespace = "http://service/", className = "client_async.CheckPay")
    @ResponseWrapper(localName = "CheckPayResponse", targetNamespace = "http://service/", className = "client_async.CheckPayResponse")
    public Response<CheckPayResponse> checkPayAsync(
        @WebParam(name = "arg0", targetNamespace = "")
        Hall arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        Boolean arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     * @param asyncHandler
     * @return
     *     returns java.util.concurrent.Future<? extends java.lang.Object>
     */
    @WebMethod(operationName = "CheckPay")
    @RequestWrapper(localName = "CheckPay", targetNamespace = "http://service/", className = "client_async.CheckPay")
    @ResponseWrapper(localName = "CheckPayResponse", targetNamespace = "http://service/", className = "client_async.CheckPayResponse")
    public Future<?> checkPayAsync(
        @WebParam(name = "arg0", targetNamespace = "")
        Hall arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        Boolean arg1,
        @WebParam(name = "asyncHandler", targetNamespace = "")
        AsyncHandler<CheckPayResponse> asyncHandler);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns client_async.Paycheck
     */
    @WebMethod(operationName = "CheckPay")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "CheckPay", targetNamespace = "http://service/", className = "client_async.CheckPay")
    @ResponseWrapper(localName = "CheckPayResponse", targetNamespace = "http://service/", className = "client_async.CheckPayResponse")
    @Action(input = "http://service/CheckPayService/CheckPayRequest", output = "http://service/CheckPayService/CheckPayResponse")
    public Paycheck checkPay(
        @WebParam(name = "arg0", targetNamespace = "")
        Hall arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        Boolean arg1);

}
