
package client_async;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "Check", targetNamespace = "http://service/", wsdlLocation = "http://localhost:9092/CheckPay?wsdl")
public class Check
    extends Service
{

    private final static URL CHECK_WSDL_LOCATION;
    private final static WebServiceException CHECK_EXCEPTION;
    private final static QName CHECK_QNAME = new QName("http://service/", "Check");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:9092/CheckPay?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CHECK_WSDL_LOCATION = url;
        CHECK_EXCEPTION = e;
    }

    public Check() {
        super(__getWsdlLocation(), CHECK_QNAME);
    }

    public Check(WebServiceFeature... features) {
        super(__getWsdlLocation(), CHECK_QNAME, features);
    }

    public Check(URL wsdlLocation) {
        super(wsdlLocation, CHECK_QNAME);
    }

    public Check(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CHECK_QNAME, features);
    }

    public Check(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Check(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns CheckPayService
     */
    @WebEndpoint(name = "CheckPort")
    public CheckPayService getCheckPort() {
        return super.getPort(new QName("http://service/", "CheckPort"), CheckPayService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CheckPayService
     */
    @WebEndpoint(name = "CheckPort")
    public CheckPayService getCheckPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://service/", "CheckPort"), CheckPayService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CHECK_EXCEPTION!= null) {
            throw CHECK_EXCEPTION;
        }
        return CHECK_WSDL_LOCATION;
    }

}
