
package client;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ReserveHallPlaceService", targetNamespace = "http://service/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ReserveHallPlaceService {


    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns client.Hall
     */
    @WebMethod(operationName = "ReservePlace")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "ReservePlace", targetNamespace = "http://service/", className = "client.ReservePlace")
    @ResponseWrapper(localName = "ReservePlaceResponse", targetNamespace = "http://service/", className = "client.ReservePlaceResponse")
    @Action(input = "http://service/ReserveHallPlaceService/ReservePlaceRequest", output = "http://service/ReserveHallPlaceService/ReservePlaceResponse")
    public Hall reservePlace(
        @WebParam(name = "arg0", targetNamespace = "")
        Hall arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        List<Integer> arg1);

}
